
<!DOCTYPE html>
<html>
  <head>
    
<meta charset="utf-8" >

<title>【JS】前端异步解决方案迭代 | PILOT</title>
<meta name="description" content="温故而知新">

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link rel="shortcut icon" href="https://null-go.github.io/favicon.ico?v=1645952268718">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.10.0/katex.min.css">
<link rel="stylesheet" href="https://null-go.github.io/styles/main.css">



<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.bootcss.com/highlight.js/9.12.0/highlight.min.js"></script>



  </head>
  <body>
    <div id="app" class="main">
      <div class="site-header-container">
  <div class="site-header">
    <div class="left">
      <a href="https://null-go.github.io">
        <img class="avatar" src="https://null-go.github.io/images/avatar.png?v=1645952268718" alt="" width="32px" height="32px">
      </a>
      <a href="https://null-go.github.io">
        <h1 class="site-title">PILOT</h1>
      </a>
    </div>
    <div class="right">
      <transition name="fade">
        <i class="icon" :class="{ 'icon-close-outline': menuVisible, 'icon-menu-outline': !menuVisible }" @click="menuVisible = !menuVisible"></i>
      </transition>
    </div>
  </div>
</div>

<transition name="fade">
  <div class="menu-container" style="display: none;" v-show="menuVisible">
    <div class="menu-list">
      
        
          <a href="/" class="menu purple-link">
            首页
          </a>
        
      
        
          <a href="/archives" class="menu purple-link">
            归档
          </a>
        
      
    </div>
  </div>
</transition>


      <div class="content-container">
        <div class="post-detail">
          
          <h2 class="post-title">【JS】前端异步解决方案迭代</h2>
          <div class="post-info post-detail-info">
            <span><i class="icon-calendar-outline"></i> 2021-10-13</span>
            
          </div>
          <div class="post-content">
            <h1 id="异步解决方案">异步解决方案</h1>
<p><strong>JS异步编程进化史：callback =》 promise =》generator =》async+await</strong></p>
<h2 id="回调函数时代">回调函数时代</h2>
<pre><code class="language-javascript">// 回调地狱
function delayExecute(str, callback = null) {
  setTimeout(() =&gt; {
    console.log(str);
    callback &amp;&amp; callback();
  }, 1000);
}
delayExecute(&quot;first execute&quot;, () =&gt; {
  delayExecute(&quot;seconde execution&quot;, () =&gt; {
    delayExecute(&quot;third execution&quot;);
  });
});
</code></pre>
<p>**优缺点：**优点是简单、容易理解和实现，缺点是不利于代码的维护，各个部分之间高度耦合，使得程序结构混乱、产生回调地狱、流程难以追踪。</p>
<h2 id="事件监听事件发布订阅">事件监听（事件发布/订阅）</h2>
<h2 id="promise-期约对象出现">Promise 期约对象出现</h2>
<h3 id="特点">特点</h3>
<ol>
<li>状态不受外界影响。<code>Promise</code>对象代表一个异步操作，有三种状态：<code>pending</code>（进行中）、<code>fulfilled</code>(很多时候称为<code>resolved</code>)（已成功）和<code>rejected</code>（已失败）。只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态。</li>
<li>一旦状态改变，就不会再变，任何时候都可以得到这个结果。<code>Promise</code>对象的状态改变，只有两种可能：从<code>pending</code>变为<code>fulfilled</code>和从<code>pending</code>变为<code>rejected</code>。只要这两种情况其中一种发生，状态就凝固了，不会再变了，会一直保持这个结果，这时就称为 resolved（已定型）。(抛出错误同样能改变状态为rejected)</li>
<li>一旦新建就立即执行，无法中途取消。</li>
</ol>
<pre><code class="language-javascript">let promise = new Promise(function(resolve, reject) {
  // executor code 
  // 这里的代码会立即执行
  /*
  if() {
  resolve();
  }
  else {
  reject();
  }
  进行一些异步操作
  */
});
</code></pre>
<ol start="4">
<li><code>resolve/reject</code> 函数只需要一个参数（或不包含任何参数），并且将忽略额外的参数。并且在resolve，reject后面的同步代码会执行，return 才会时 executor 函数停止。</li>
<li><strong>throw</strong> 抛出任何东西相当于 <code>reject()</code>，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。</li>
</ol>
<blockquote>
<p>如果状态改变已经发生了，再对<code>Promise</code>对象添加回调函数，也会立即得到这个结果。这与事件（Event）完全不同，事件的特点是，如果你错过了它，再去监听，是得不到结果的。</p>
</blockquote>
<h3 id="基本用法">基本用法</h3>
<p><code>Promise</code>对象是一个构造函数，用来生成<code>Promise</code>实例。</p>
<p><code>Promise</code>构造函数接受一个函数作为参数，该函数的两个参数分别是<code>resolve</code>和<code>reject</code>。它们是两个函数，由 JavaScript 引擎提供，不用自己部署。<code>resolve</code>函数把<code>Promise</code>对象的状态从<code>pending</code>变为<code>fulfilled</code>,reject函数把<code>Promise</code>对象的状态从<code>pending</code>变为<code>rejected</code></p>
<h3 id="链式调用及错误处理">[链式调用]及[错误处理]</h3>
<h4 id="then-thenonfulfilledonrejected">.then then(onFulfilled,onRejected)</h4>
<p>**.then 方法：**接受两个回调函数(均可选)，第一个回调函数在状态变为<code>fulfilled</code>时调用，第二个回调函数在状态变为<code>rejected</code>时调用。也可以只传入一个函数。</p>
<figure data-type="image" tabindex="1"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210407220550670.png" alt="image-20210407220550670" loading="lazy"></figure>
<p><strong>.then：</strong> 特别注意这个新的<code>Promise</code>对象将以回调的返回值来 <code>resolve</code>自己，无论是onFulfilled回调函数还是onRejected回调函数（ 相当于调用了 <code>Promise.resolve()</code> 方法，<code>Promise.resolve()</code>对Promise对象具有幂等性，具体看下面的API介绍，这里虽然行为像是 <code>Promise.resolve</code>方法，但是返回的并不是同一个Promise，和实际上的<code>Promise.resolve</code>不一样）( <strong>代码一</strong>，所以此时的then会立即执行 )。若返回一个新Promise对象，相当于把默认的行为取消掉了， .then 方法返回一个<strong>等价的Promise</strong>，如下图( <strong>代码二</strong>，此时的then会等到返回的promise对象状态改变时执行。</p>
<img src="C:\Users\huangzhehao\AppData\Roaming\Typora\typora-user-images\image-20210426193506089.png" alt="image-20210426193506089" style="zoom:80%;" />
<pre><code class="language-javascript">new Promise((resolve) =&gt; {
  resolve(1);
})
  .then((result) =&gt; {
    console.log(result); //输出 1
    return result * 2; //.then 创建的promise对象默认return 即 resolve 了;
  })
  .then((result) =&gt; {
    console.log(result); // 输出 2
    return result * 2;
  });
</code></pre>
<p>我们可以在 <code>.then</code> 中显示的创建一个新的<code>Promise</code> 对象并 <code>return</code></p>
<pre><code class="language-javascript">new Promise((resolve) =&gt; {
  resolve(1);
})
  .then((result) =&gt; {
    console.log(result); //输出 1
    return new Promise((resolve) =&gt; {
      setTimeout(() =&gt; {
        resolve(result * 2);
      }, 1000);
    }); // 改造成显示的 return 一个新的promise 对象
  })
  .then((result) =&gt; {
    console.log(result); // 输出 2 有一秒的延迟
    return result * 2;
  });
</code></pre>
<p>为什么 .then 函数 onRejced 回调函数中返回值仍然使用 <code>Promise.resolve()</code> 来返回呢？原因： .then 处理程序 onRejced 回调函数的目的就是捕获异步错误，因此，不抛出异常是符合期约的行为，应该返回一个解决的期约。</p>
<p><strong>当.then() 函数不传参：</strong></p>
<figure data-type="image" tabindex="2"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210809171906854.png" alt="image-20210809171906854" loading="lazy"></figure>
<p>.then 可以绑定多个回调函数，按照绑定顺序依次执行。</p>
<h4 id="catch-catchonrejected">.catch catch(onRejected)</h4>
<p><code>.catch</code>的行为等价于 .then(null,onRejected)。</p>
<img src="C:\Users\huangzhehao\AppData\Roaming\Typora\typora-user-images\image-20210408211116447.png" alt="image-20210408211116447" style="zoom:80%;" />
<p>使用 <code>throw</code>语法抛出<code>Error</code>错误，catch 可以接收到。throw 抛出的错误会一直向链后冒泡，直到<code>.then</code>中的第二个函数捕获或catch方法捕获。</p>
<pre><code class="language-javascript">// 抛出错误
new Promise((resolve,reject)=&gt;{
  throw new Error('抛出错误');
  // 等价于
  reject(new Error('抛出错误'));
})
</code></pre>
<p>当在<strong>Promise</strong>中抛出了错误（或产生了语法错误）却没有被捕获时，JavaScript 引擎会跟踪此类 rejection，在这种情况下会生成一个全局的 error。这个error不会影响外部代码的继续执行。</p>
<p>看下列问题：</p>
<figure data-type="image" tabindex="3"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210408220448045.png" alt="image-20210408220448045" loading="lazy"></figure>
<p>.catch 会被触发吗？不会。<strong>在Promise内同步的代码抛出的错误会被当成 rejected来处理，所有同步的错误可以被catch到</strong>，但现在不是同步的，故catch无法捕获错误( 控制台会打印出错误 )，但是setTimeout中的reject可以被捕获。</p>
<h4 id="finally-finallyonfinally">.finally finally(onFinally)</h4>
<p><code>finally()</code>是在promise结束时，无论结果是fulfilled或者是rejected，都会执行指定的回调函数（即<code>onFinally</code>）。</p>
<p><code>onFlinally</code> 回调函数<strong>不接受任何参数</strong>。它仅用于无论最终结果如何都要执行的情况。这表明，<code>finally</code>里的操作应该是不依赖于<code>Promise</code>状态和执行结果的。</p>
<p>因为 onFinally 被设计为一个状态无关的方法，所以在大多数情况下它将表现为<strong>父期约的传递</strong>。而不像 .then .catch 方法那样会进行返回值的<code>Promise.resolve</code>包装。</p>
<pre><code class="language-javascript">Promise.resolve(&quot;1&quot;)
  .then(res =&gt; {
    return new Promise(resolve =&gt; {});
  })
  .finally(() =&gt; {
    console.log(&quot;finally&quot;);
  });
Promise.resolve(&quot;2&quot;)
  .finally(() =&gt; {
    console.log(&quot;finally2&quot;);
    return &quot;我是finally2返回的值&quot;;
  })
  .then(res =&gt; {
    console.log(&quot;finally2后面的then函数&quot;, res);
  });
</code></pre>
<h4 id="关于-then-方法的一个疑难问题解决">关于 then 方法的一个疑难问题解决</h4>
<p><strong>变量 innerPromise 是 then 方法的返回值吗：答是的。在一次进入函数时，then 方法就已经执行了，注册了 then 的回调函数，innerPromise 就是 then 回调函数的返回值。</strong></p>
<pre><code class="language-javascript">let innerPromise;
function getAThenPromise() {
  innerPromise = new Promise(resolve =&gt; {
    setTimeout(() =&gt; {
      console.log(&quot;宏1&quot;);
      resolve(&quot;value&quot;);
    }, 2000);
  }).then(() =&gt; {
    console.log(&quot;微1&quot;);
    return new Promise(resolve =&gt; {
      setTimeout(() =&gt; {
        console.log(&quot;宏2&quot;);
        resolve(&quot;value3&quot;);
      });
    });
  });
  return innerPromise;
}
let outerPromise = getAThenPromise();
console.log(outerPromise); // 观察值，开始是 pending，后面变成 fulfilled。
outerPromise.then(value =&gt; {
  console.log(&quot;微2&quot;);
  console.log(value);
});
console.log(innerPromise === outerPromise);
</code></pre>
<pre><code class="language-javascript">// true
// 宏1
// 微1
// 宏2
// 微2
// value3
</code></pre>
<ul>
<li>在还没结束时点开 <code>innerPromise</code>:</li>
</ul>
<figure data-type="image" tabindex="4"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20211129113604364.png" alt="image-20211129113604364" loading="lazy"></figure>
<p>之后全部输出完了这个值还固定着，</p>
<figure data-type="image" tabindex="5"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20211129113631116.png" alt="image-20211129113631116" loading="lazy"></figure>
<ul>
<li>在输出完之后再点开 innerPromise</li>
</ul>
<figure data-type="image" tabindex="6"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20211129113708112.png" alt="image-20211129113708112" loading="lazy"></figure>
<h3 id="常见api">常见API</h3>
<h4 id="promiseall">Promise.all()</h4>
<p>参数：可迭代的Promise对象(通常传递数组)</p>
<p>返回值：一个新的Promise对象</p>
<ul>
<li>
<p>返回值的Promise对象：<code>resolve</code>回调执行是在所有输入的promise的resolve回调都结束，返回值是传入的Promise参数数组全部resolve的值组成的数组;<code>reject</code>回调执行是，只要任何一个输入的promise的reject回调执行或者输入不合法的promise就会立即抛出错误，并且reject的是第一个抛出的错误信息。</p>
</li>
<li>
<p>结果数组中元素的顺序与其在源 promise 中的顺序相同。即使第一个 promise 花费了最长的时间才 resolve，但它仍是结果数组中的第一个。</p>
</li>
<li>
<p>如果传入的可迭代对象为空，<code>Promise.all</code> 会同步地返回一个已完成（resolved）状态的<code>promise</code>。</p>
</li>
<li>
<p>如果参数中包含非 <code>promise</code> 值，这些值将被忽略，但仍然会被放在返回数组中（如果 <code>promise</code> 完成的话）</p>
</li>
</ul>
<h4 id="promiserace">Promise.race()</h4>
<p>与 <code>Promise.all</code> 类似，但只等待第一个 settled（resolved或rejected） 的 promise 并获取其结果（或 error）。</p>
<h4 id="promiseresolvevalue-rejectvalue">Promise.resolve(value) / reject(value)</h4>
<ul>
<li>对于<code>Promise.resolve()</code>，如果value是定值，结果返回用 <code>value</code> 创建的一个 resolved 的 promise。如同：</li>
</ul>
<pre><code class="language-javascript">Promise.resolve(value);
let promise = new Promise(resolve =&gt; resolve(value));
</code></pre>
<p>这个方法能够包装<strong>任何非期约值</strong>，包括错误对象，并将其转换为解决的期约值，因此，也可能导致不符合预期的行为：</p>
<pre><code class="language-javascript">let p = Promise.resolve(new Error('foo')); 
setTimeout(console.log, 0, p); 
// Promise &lt;resolved&gt;: Error: foo
</code></pre>
<p>对于<code>Promise.resolve()</code>逻辑而言，它是<code>幂等</code>逻辑，如果value是一个Promise，它将返回这个Promise。如果这个值是 <strong>thenable</strong>（即带有then方法），返回的promise会“跟随”这个<strong>thenable</strong>的对象，采用它的最终状态。</p>
<pre><code class="language-javascript">let thenable = {
  then: function(resolve, reject) {
    resolve(42);
  }
};

let p1 = Promise.resolve(thenable);
p1.then(function (value) {
  console.log(value);  // 42
});
</code></pre>
<p>多余的参数将被忽略。</p>
<ul>
<li>
<p>对于 <code>Promise.reject()</code>与 <code>Promise.resolve()</code>类似，Promise.reject()会实例化一个拒绝的期约并抛出一个异步错误。（这个错误不能通过 try/catch 捕获，而只能通过拒绝处理程序捕获）。</p>
<p>但是对于 <code>Promise.reject()</code>逻辑而言，它不是幂等逻辑，如果value是一个Promise，它不会返回这个Promise，而是将这个Promise作为它rejected的理由（也就是reject函数的参数）。</p>
</li>
</ul>
<h3 id="promise-包装器-promisify">Promise 包装器 Promisify</h3>
<p>将 callBack 语法的 API 改成 Promise 语法。</p>
<pre><code class="language-javascript">// 原来 callBack 语法的API
function loadScript(src, callback) {
  let script = document.createElement('script');
  script.src = src;

  script.onload = () =&gt; callback(null, script);
  script.onerror = () =&gt; callback(new Error(`Script load error for ${src}`));

  document.head.append(script);
}
// 用法：
// loadScript('path/script.js', (err, script) =&gt; {...})
</code></pre>
<pre><code class="language-javascript">// 传入需要 Promise 化函数的 originalFun
// originalFun 第一个参数为自定义参数，第二个参数是回调函数
// originalFun 函数中的 回调函数第一个参数是错误信息
function Promisify(originalFun) {
  // 返回一个包装函数（wrapper-function),此函数不用传递第二个参数：回调函数
  return function (...args) {
    return new Promise((resolve, reject) =&gt; {
      // 自定义回调函数，传入 originalFun
      function callBack(err, result) {
        if (err) {
          reject(err);
        } else {
          resolve(result);
        }
      }
      // 将自定义的 callBack 附加到参数末尾
      args.push(callBack);
      // 调用原始函数
      originalFun.call(this, ...args);
    });
  };
}
</code></pre>
<h3 id="微任务-microtask">微任务 Microtask</h3>
<pre><code class="language-javascript">let p = Promise.resolve(3);
p.then((res) =&gt; {
  console.log(res);
});
console.log(&quot;code finished&quot;);
// 先输出 code finished 后输出3
</code></pre>
<p><strong>异步任务需要适当的管理。为此，ECMA 标准规定了一个内部队列 <code>PromiseJobs</code>，通常被称为“微任务队列（microtask queue）”（ES8 术语）。</strong></p>
<ul>
<li>队列是先进先出的，首先进入队列的任务会先被执行。</li>
<li>只有在JavaScript引擎没有其他任务运行时，微任务队列中的任务才会被执行。</li>
</ul>
<h2 id="generator-function-和-生成器对象">Generator function 和 生成器对象</h2>
<p><strong>Generator函数是ES6提供的一种异步编程解决方案，语法行为和传统函数不同，最大的特点即是可以控制函数的执行。（Generator函数底层利用协程来控制函数的执行流程，【浏览器】浏览器工作原理与实践.md 详解）</strong></p>
<h3 id="generator函数生成器函数-function">Generator函数(生成器函数)  function*</h3>
<p>Generator 函数与常规函数的行为不同。在此类函数被调用时，它<strong>不会运行其代码</strong>。而是返回一个被称为''<strong>generator object</strong>''的特殊对象，来管理执行流程。</p>
<p><strong>生成器函数：生成器函数是一个状态机，封装了多个内部状态，执行生成器函数可以产生<code>生成器对象</code>的函数。生成器对象符合可迭代协议和迭代器协议，他们是可迭代的。</strong></p>
<pre><code class="language-javascript">function* generateSequence() {
  yield 1;
  yield 2;
  return 3;
}
// &quot;generator function&quot; 创建了一个 &quot;generator object&quot;
let generator = generateSequence();
alert(generator); // [object Generator]
</code></pre>
<h4 id="next-方法">next() 方法</h4>
<p>当 <code>next()</code> 被调用时，Generator函数运行到第一个 <strong>yield</strong> 结束之前。返回一个对象，该对象有两个属性：</p>
<ul>
<li>
<p><code>value</code>属性即 yield 后跟的值(没有值默认为undefined)。</p>
</li>
<li>
<p><code>done</code>属性即 <code>generator</code> 函数是否执行完。</p>
</li>
</ul>
<p>当 generator 函数执行到 return 语句时，函数结束(没有return 默认最后return undefined，这与普通函数一致)。</p>
<blockquote>
<p>return 后的值也是一个对象，与yield类似，value属性为return的值，done属性为true。</p>
<p>如果我们在 return 后再次调用 next() 方法，同样返回最后一次return 的结果。</p>
</blockquote>
<h3 id="generator-是可迭代的">Generator 是可迭代的</h3>
<p>因为 Generator 对象是可迭代的，所有它可以使用所有可迭代对象的通用方法。</p>
<ol>
<li>使用 for of 遍历 Generator  对象</li>
</ol>
<p><code>done: true</code> 时，<code>for..of</code> 循环会忽略最后一个 <code>value</code>。因此，如果我们想要通过 <code>for..of</code> 循环显示的结果，我们必须使用 <code>yield</code> 返回它们。</p>
<ol start="2">
<li>使用 <code>...spread</code> 语法</li>
</ol>
<p>同样会忽略 <code>done:true</code>的值。</p>
<h4 id="generator-和-iterator-的比较">Generator 和 iterator 的比较:</h4>
<p><strong>iterator：</strong></p>
<pre><code class="language-javascript">let range = {
  from: 1,
  to: 5,
  // for..of range 在一开始就调用一次这个方法 生成迭代器对象 iterator object
  [Symbol.iterator]() {
    // ...它返回 iterator object：
    // 后续的操作中，for..of 将只针对这个对象，并使用 next() 向它请求下一个值
    return {
      current: this.from,
      last: this.to,
      // for..of 循环在每次迭代时都会调用 next()
      next() {
        // 它应该以对象 {done:.., value :...} 的形式返回值
        if (this.current &lt;= this.last) {
          return { value: this.current++, done: false };
        } else {
          return { value: this.current, done: true };
        }
      },
    };
  },
};
for (item of range) {
  console.log(item); // 输出 1 2 3 4 5
}
console.log([...range]); // 输出 [1,2,3,4,5]
</code></pre>
<p><strong>Generator：</strong></p>
<pre><code class="language-javascript">let range = {
  from: 1,
  to: 5,
  // 调用该方法直接返回了一个 迭代器对象 iterator Object
  *[Symbol.iterator]() {
    for (; this.from &lt;= this.to; this.from++) yield this.from; //yield相当于next()
  },
};
for (item of range) {
  console.log(item); // 输出 1 2 3 4 5
}
console.log([...range]); // 输出 [] 空数组 因为循环不会执行，又没有除return undefined以外的返回值了
</code></pre>
<p>因为 <code>[Symbol.iterator]</code> 方法现在 带 * 号，直接返回了一个迭代器对象 (</p>
<ul>
<li>它具有 <code>.next()</code> 方法 （Generator对象本身，隐式的）</li>
<li>next 方法有 <code>{value: ..., done: true/false}</code> 形式的返回值 （yield关键字实现的）</li>
</ul>
<p>)</p>
<h3 id="generator-组合">Generator 组合</h3>
<p>Generator 组合（composition）是 generator 的一个特殊功能，它允许透明地（transparently）将 generator 彼此“嵌入（embed）”到一起。</p>
<p>通过 yield* 实现：</p>
<pre><code class="language-javascript">function* aGeneratorMake(start, end) {
  for (let i = start; i &lt;= end; i++) {
    yield i;
  }
}
function* bGeneratorMake() {
  yield* aGeneratorMake(1, 3);
  yield* aGeneratorMake(4, 5);
}
let result = [];
for (item of bGeneratorMake()) {
  result.push(item);
}
console.log(result); // [1,2,3,4,5]
</code></pre>
<p><code>yield*</code> 指令将执行 <strong>委托</strong> 给另一个 generator。这个术语意味着 <code>yield* gen</code> 在 generator <code>gen</code> 上进行迭代，并将其产出（yield）的值透明地（transparently）转发到外部。就好像这些值就是由外部的 generator yield 的一样。</p>
<p>Generator 组合（composition）是将一个 generator 流插入到另一个 generator 流的自然的方式。它不需要使用额外的内存来存储中间结果。<br>
<code>yiled*</code> 后面还能跟其他可迭代对象：</p>
<pre><code class="language-javascript">function* gen() {
  yield* [1, 2, 3];
}
function* gen2() {
  yield* &quot;GOD&quot;;
}
for (let item of gen()) {
  console.log(item); //1 2 3
}
for (let item of gen2()) {
  console.log(item); //GOD
}
</code></pre>
<h3 id="yield-是条双向路"><code>yield</code> 是条双向路</h3>
<p><code>yield</code>不仅可以将值传递到<code>generator</code>外面，还能从<code>generator</code>外面将值传入到里面。</p>
<p>调用 generator.next(arg);</p>
<img src="C:\Users\huangzhehao\AppData\Roaming\Typora\typora-user-images\image-20210413093734515.png" alt="image-20210413093734515" style="zoom: 67%;" />
<p>**即：**当调用的是<code>next(arg)</code>,next包含参数，除第一次会忽略外，<code>arg</code>参数将会成为当前停止的yield的返回值。</p>
<h3 id="异步可迭代对象">异步可迭代对象</h3>
<p>改造可迭代对象：</p>
<ol>
<li>使用 <code>Symbol.asyncIterator</code> 取代 <code>Symbol.iterator</code>。</li>
<li><code>next()</code> 方法应该返回一个 <code>promise</code>（带有下一个值，并且状态为 <code>fulfilled</code>）。
<ul>
<li>关键字 <code>async</code> 可以实现这一点，我们可以简单地使用 <code>async next()</code>。</li>
<li>tip:<strong>因为我们必须保证next方法返回的是一个Promise，若不用 <code>async next()</code>而直接用单纯的<code>next()</code>,我们必须显式的返回一个Promise对象,<code>async</code>隐式的返回了一个Promise(fulfilled)</strong></li>
</ul>
</li>
<li>我们应该使用 <code>for await (let item of iterable)</code> 循环来迭代这样的对象。
<ul>
<li>注意关键字 <code>await</code>。</li>
<li>tip:<strong><code>await</code>是因为在next方法中返回的Promise，await可以得到Promise的值</strong></li>
</ul>
</li>
</ol>
<pre><code class="language-javascript">let obj = {
  first: 1,
  last: 5,
  // 将 Symbol.iterator 方法改为 Symbol.asyncIterator 方法
  [Symbol.asyncIterator]() {
    return {
      fir: this.first,
      lat: this.last,
      async next() {   // next 方法改为 async next
        await new Promise((resolve, reject) =&gt; {  // 可以在next方法中使用await了
          setTimeout(resolve, 1000);
        });
        if (this.fir &lt;= this.lat) {
          return {
            value: this.fir++,
            done: false,
          };
        } else {
          return {
            value: this.fir++,
            done: true,
          };
        }
      },
    };
  },
};
(async () =&gt; { // 创建一个async函数
  for await (const iterator of obj) { // await类型的 for of 循环可以使用了
    console.log(iterator);
  }
})();

// next 不加 async 关键词
next() {
  if (this.fir &lt;= this.lat) {
    return new Promise((resolve) =&gt; {
      resolve({
        value: this.fir++,
        done: false,
      });
    });
  } else {
    return new Promise((resolve) =&gt; {
      resolve({
        value: this.fir++,
        done: true,
      });
    });
  }
}
</code></pre>
<p>当使用<code>for of</code>时，它希望找到的是 <code>[Symbol.iterator]</code>方法，当使用 <code>async + for await for</code>时，它希望找到的是<code>[Symbol.asyncIterator]</code>方法。</p>
<h3 id="异步-generator">异步 Generator</h3>
<p>在<code>*function</code>前加上<code>async</code>，使生成器函数称为异步生成器函数。</p>
<pre><code class="language-javascript">async function* generatorMaker() {
  for (let i = 1; i &lt;= 5; i++) {
    // 显示的 yield promise
    yield new Promise((resolve) =&gt; {
      setTimeout(() =&gt; {
        resolve(i);
      }, 1000);
    });
    // yield i; 这是隐式的yield Promise，因为async函数的缘故 
  }
}
let gener = generatorMaker();
// 为了 用await接收 异步生成器函数 yield 回来的 Promise对象，创建了一个匿名的async函数
(async () =&gt; {
  let anwser = await gener.next();
  console.log(anwser); // 输出 {value : 1 ,done : false}
  for await (let item of gener) console.log(item); // 输出 2 3 4 5  for循环中只会返回 value部分
})();
</code></pre>
<figure data-type="image" tabindex="7"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210416151201755.png" alt="image-20210416151201755" loading="lazy"></figure>
<h2 id="async-await">async | await</h2>
<p><strong>提供了在不阻塞主线程的情况下使用同步代码实现异步访问资源的能力，并且使得代码逻辑更加清晰，而且还支持 try-catch 来捕获异常，非常符合人的思维。</strong></p>
<h4 id="async-function">async function</h4>
<pre><code class="language-javascript">async function f(){
    return {name:'黄'};
}
// &lt;-&gt; 等价于
function f(){
    return Promise.resolve({name:'黄'}); 
}
// 通过 .then 拿到async函数的返回值
f().then(result=&gt;{
    console.log(result); // 输出 {name:'黄'}
})
</code></pre>
<p><strong>async函数一定会返回一个Promise对象，如果一个async函数的返回值看起来不是promise，那么它将会被隐式地包装在一个promise.resolve()，类似于.then() 方法。</strong></p>
<h4 id="只在async函数内起作用的await">只在async函数内起作用的await</h4>
<p><code>async</code>/<code>await</code>的目的为了简化使用基于promise的API时所需的语法。</p>
<p><strong>Promise 虽然解决的回调，充斥着大量的 then 方法，于是出现了 async/await</strong></p>
<p>await代替我们进行了等待，就像<code>.then</code>和<code>.catch</code>此类方法中传入的回调函数的参数，<code>async</code>/<code>await</code>的行为就好像搭配使用了<strong>生成器和promise</strong>（<code>async/await</code>就像是 <strong>Generator搭配Promise的语法糖（代替了Generator函数的出现，async 函数就是将 Generator 函数的星号（*）替换成 async，将 yield 替换成 await）</strong>）。</p>
<pre><code class="language-javascript">// await
let result = await new Promise((resolve,reject)=&gt;{
     resolve(11); // 直接拿到Promise执行后的结果了 不需要.then 
})
</code></pre>
<figure data-type="image" tabindex="8"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210829150030706.png" alt="image-20210829150030706" loading="lazy"></figure>
<p><strong>await表达式会暂停整个async函数的执行进程并出让其控制权(交给外部函数)，只有当其等待的基于promise的异步操作被兑现或被拒绝之后才会恢复进程。当await将async函数执行进程暂停时，JavaScript 引擎可以同时处理其他任务：执行其他脚本，处理事件</strong></p>
<p><strong>await后跟一个promise，该promise的解决值会被当作该await表达式的返回值。后若不是Promise，则用 Promise.resolve() 包装。此外，await 后面的代码相当于放入了 Promise的.then 函数中，因此后面的代码被提交到微任务列表中。</strong></p>
<pre><code class="language-javascript">async function genpro() {
  await new Promise(resolve =&gt; {
    resolve(&quot;yield Promise&quot;);
  });
  console.log(&quot;await 后面被包裹是微任务&quot;);
}
</code></pre>
<p><strong>如果一个 promise 正常 resolve，<code>await promise</code> 返回的就是其结果。但是如果 promise 被 reject，它将 throw 这个 error，就像在这一行有一个 <code>throw</code> 语句那样。</strong></p>
<pre><code class="language-javascript">// await 后的Promise被 reject了
async function f() {
  await Promise.reject(new Error(&quot;Whoops!&quot;));
}
// &lt;-&gt; 等价于 
async function f(){
  throw new Error(&quot;Whoops!&quot;)  
}
// await 中的Promise抛出了错误
async function foo() {
  await new Promise((resolve, reject) =&gt; {
    resolve(1);
  });
  await new Promise((resolve, reject) =&gt; {
    resolve(2);
  });
  await new Promise((resolve, reject) =&gt; {
    reject(new Error(&quot;错误&quot;));  // &lt;-等价于-&gt; throw new Error(&quot;错误&quot;);
  });
}
foo().then(null, (error) =&gt; {
  console.log(error);   // 拿到了错误 
});
</code></pre>
<figure data-type="image" tabindex="9"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210410142832659.png" alt="image-20210410142832659" loading="lazy"></figure>
<p>上述 foo() 调用过程中，第三个<code>await</code>后接的Promise被rejected了，<strong>该async函数隐式返回了一个被rejected的Promise对象</strong>。这说明了在<code>async</code>中多次使用<code>await</code>，若有<code>await</code>后跟的Promise对象抛出了错误或者是rejected了。async函数它将自动捕获异常，<strong>async函数执行中断</strong>，并通过隐式返回rejected Promise将错误传递给出去。</p>
<blockquote>
<p>关于 await 后面的代码运行顺序的考量：</p>
<p>https://juejin.cn/post/6844903988584775693#heading-1；</p>
<p>https://www.zhihu.com/question/268007969</p>
<p>根据 TC39 最近决议，await将直接使用Promise.resolve() 相同语义</p>
</blockquote>
<figure data-type="image" tabindex="10"><img src="C:%5CUsers%5Chuangzhehao%5CAppData%5CRoaming%5CTypora%5Ctypora-user-images%5Cimage-20210810095834695.png" alt="image-20210810095834695" loading="lazy"></figure>

          </div>
        </div>

        
          <div class="next-post">
            <a class="purple-link" href="https://null-go.github.io/post/gong-cheng-hua-qian-xue-webpack/">
              <h3 class="post-title">
                下一篇：【工程化】浅学 Webpack
              </h3>
            </a>
          </div>
          
      </div>

      

      <div class="site-footer">
  <div class="slogan">温故而知新</div>
  <div class="social-container">
    
      
    
      
    
      
    
      
    
      
    
  </div>
  Powered by <a href="https://github.com/getgridea/gridea" target="_blank">Gridea</a> | <a class="rss" href="https://null-go.github.io/atom.xml" target="_blank">RSS</a>
</div>


    </div>
    <script type="application/javascript">

hljs.initHighlightingOnLoad()

var app = new Vue({
  el: '#app',
  data: {
    menuVisible: false,
  },
})

</script>




  </body>
</html>
